### ISSUE TITLE
How To Build Project

### ISSUE THREAD

**Issue by holmanb** [unfa/Sho#1]
I don't see any build instructions, but I figured I'd give it a try anyway following the [godot instructions](https://docs.godotengine.org/en/stable/development/compiling/compiling_for_x11.html)

I'm assuming SConstruct just needs to be included based on the error.

```
$ scons -j$(nproc) platform=x11

scons: *** No SConstruct file found.
File "/usr/lib/python3.9/site-packages/SCons/Script/Main.py", line 947, in _main
$ scons -u -j$(nproc) platform=x11

scons: *** No SConstruct file found.
File "/usr/lib/python3.9/site-packages/SCons/Script/Main.py", line 947, in _main

```

**Comment by unfa** [comment]
Sorry, I should tidy up the repo a bit and fill in the information. I didn't have time to do that yet.

Please note that I'm not really a programmer and my work is quite messy.

To play the game you need the Godot editor. Download the "stable" branch, and open it in Godot as a project. Then you can export the game to an executable file - this is how you'd make a build.

Or you can just play the game from the editor.

**Comment by unfa** [comment]
I've now cleaned up the repository. Got rid of the `stable` branch and merged it into `master`and provided binary downloads in `releasaes`.
