### ISSUE TITLE
Mint.dae missing

### ISSUE THREAD

**Issue by xard-dev** [unfa/Sho#11]
Pulled the git repository and tried opening the project with full godot editor and it refuses to load as it claims res://Assets/Mint/Mint.dae is missing.

Checked the Sho/Assets/Mint and sure enough, there's no such model and the scene Mint.tscn tries to import it.

**Comment by xard-dev** [comment]
Manually replacing the asset to point out "res://Assets/Mint/Mint.gltf" model (which does exist) seems to fix the issue.

**Comment by unfa** [comment]
Ah, yeah, I've used .dae before, but moved on to .gltf - this reference must be outdated, I'll check that.

**Comment by unfa** [comment]
Should be fixed? Closing for now. If the problem persists - let's reopen.
