### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by holmanb** [unfa/Sho#7]
Neat game!

The game crashed on level 2 for me
here's a log of x-session errors that appear related:

https://pastebin.com/QKEDARsY

Stable branch

godot version:  3.2.1 (fedora)

**Comment by unfa** [comment]
Hi! Th stable branch no longer exists :D Did this happen in a released build?

**Comment by unfa** [comment]
It seems the game couldn't load `MoverTrigger.tscn` - it might have not been commited in that version. Could you try a released build or current master branch?
